ackermann_controller:
  ros__parameters:
    reference_timeout: 0.5

    front_steering: true
    rear_steering: false

    front_wheels:
      - left_front_wheel_joint
      - right_front_wheel_joint

    rear_wheels:
      - left_rear_wheel_joint
      - right_rear_wheel_joint

    wheelbase: 0.32        # distancia entre ejes
    front_track: 0.25      # ancho delantero
    rear_track: 0.25

    wheel_radius: 0.073    # di√°metro / 2

    cmd_vel_timeout: 0.5
    publish_rate: 50
