controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    steering_position_controller:
      type: forward_command_controller/ForwardCommandController

    rear_wheel_pid:
      type: pid_controller/PidController

steering_position_controller:
  ros__parameters:
    joints: [left_steering_joint, right_steering_joint]
    interface_name: position

rear_wheel_pid:
  ros__parameters:
    dof_names: [left_rear_axle, right_rear_axle]
    command_interface: velocity
    reference_and_state_interfaces: ["velocity"]
    gains:
      left_rear_axle: {p: 0.9, i: 10.0, d: 0.0, feedforward_gain: 1.0}
      right_rear_axle: {p: 0.9, i: 10.0, d: 0.0, feedforward_gain: 1.0}