controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ackermann_steering_controller:
  ros__parameters:
    type: 'ackermann_steering_controller/AckermannSteeringController'
    wheelbase: 0.335
    traction_track_width: 0.365
    steering_track_width: 0.365
    traction_wheels_radius: 0.073025
    steering_wheels_radius: 0.073025
    reference_timeout: 2.0 # In s. Timeout to stop if no cmd_vel is received
    traction_joints_names: ['right_rear_axle', 'left_rear_axle']
    steering_joints_names: ['right_steering_joint', 'left_steering_joint']
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.02, 0.02, 0.1, 0.1, 0.1, 0.02]
    pose_covariance_diagonal:  [0.02, 0.02, 0.1, 0.1, 0.1, 0.02]
    position_feedback: false